### ISSUE TITLE
Site keywords should not appear as meta keywords on blog posts

### ISSUE THREAD

**Issue by tabitagreen** [carleton/reason_package#106]
Keywords entered on a given site, show up on posts originating on the same site. For example, here is a line from the source from https://www.luther.edu/ideas-creations-blog/?story_id=605647:

<meta name="keywords" content="faculty blog, blogs" />

Meta keywords should not appear on posts. It's generally not good for SEO.

**Comment by mryand** [comment]
The way this issue is described is not quite accurate. What is happening, specifically, is this:

The default template, on site home pages, falls back to using the site entity's keywords in the keywords field if there are no page keywords supplied. This appears to be independent of blogs or any other module.

I propose that we close this issue and create a new one with the title "Add a setting to turn off the meta keywords field globally" and note that the main place this should be implemented is in get_meta_information() on the default module.
