### ISSUE TITLE
VM: Virtual Box VM doesn't setup networking correctly

### ISSUE THREAD

**Issue by slylth** [carleton/reason_package#151]
Spinning up the VM doesn't provide a good IP for running the server. 

``` Could not get an IP address via DHCP - chech VM network settings.```

## Steps to reproduce
- Download VM
- Start VM
- Environment info
  - Mac OS X - Yosemite 10.10.4
  - VirtualBox 5
  - ReasonCMS-4.5 VM

**Comment by slylth** [comment]
# Fix for the IP issue
- add a second adapter
![screen shot 2015-07-28 at 3 24 42 pm](https://cloud.githubusercontent.com/assets/1071533/8995719/dbcd0f6a-36d8-11e5-9385-be8730807a59.png)
- boot
- delete /etc/udev/rules.d/70-persistent-net.rules
- reboot
- export VM

**Comment by slylth** [comment]
Another networking issue the guest machine can't access the internet. I think this is a problem with the not having an eth0 setup.

**Comment by slylth** [comment]
http://serverfault.com/questions/437908/virtualbox-inbound-network-connections-failing

**Comment by slylth** [comment]
This is not just a Mac issue. Same results on a Windows machine.

**Comment by DookTibsCarl** [comment]
Working on this on a Macbook Air turned up another issue that should maybe be documented - you get the following error on VM startup:
---
Could not start the machine ReasonCMS-4.5 because the following physical
network interfaces were not found:
en1: Wi-Fi (AirPort) (adapter 1)
You can either change the machine's network settings or stop the machine.
---

No physical ethernet interface on that machine so the wifi adapter is actually en0. Gotta edit VirtualBox settings and basically just save without changing anything to force a switch from en1 to en0.

**Comment by DookTibsCarl** [comment]
beyond that - not sure if this is worthwhile or not. For adding the second adapter as described above, rather than "host-only", I tried using just plain NAT. This gives guest os network access - I'm able to pull webpages with curl from command line as a test. Guest os IP changes from a 192.168.* to a 10.0.* though, and I'm no longer able to access the guest machine from the host machine.

Doing port forwarding on the second adapter (protocol TCP, host 127.0.0.1:8765, guest 10.0.3.15:80) I'm able to get around this. After that, from host machine I can do http://127.0.0.1:8765/login/ and log into the reason instance.

This seems sorta clunky so not sure if it's worth going this route?

**Comment by slylth** [comment]
I added the following to the thank you message on reasoncms.org
- __Please Note__ - The networking is behaving a little flaky, especially when only using wi-fi. Follow these instructions to fix.
  - Open Settings for the VM
  - Click OK
  - Start the VM
  - That's it!
